name = "Watershed"
uuid = "de0ec347-3b5a-4f0f-8861-85d9ef41faeb"
authors = ["Administrator "]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
